### ISSUE TITLE
pdf export ภาษาไทยเพี้ยนในส่วน thread entry

### ISSUE THREAD

**Issue by SolidK0RE** [trc-skw/iservice#16]
![capture](https://cloud.githubusercontent.com/assets/9249682/7557698/56b16012-f7c0-11e4-9ed3-8432eb0c68de.JPG)

**Comment by enividlived** [comment]
![pdfcommentfontthai](https://cloud.githubusercontent.com/assets/10202947/7558634/0e5298f0-f7d3-11e4-8d31-f9de74ef4973.JPG)

ดำเนินการแล้วจ้า
